apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-manage-bingewatching
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ "role-template-view-bingewatching" ]
    rbac.authorization.halo.run/module: "追剧"
    rbac.authorization.halo.run/display-name: "追剧管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:bingewatching:manage"]
rules:
  - apiGroups: [ "bingewatching.lik.cc" ]
    resources: [ "handsomemovies" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]

---

apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-view-bingewatching
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "追剧"
    rbac.authorization.halo.run/display-name: "追剧查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:bingewatching:view"]
rules:
  - apiGroups: [ "bingewatching.lik.cc" ]
    resources: [ "handsomemovies" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.bingewatching.lik.cc" ]
    resources: [ "movies" ]
    verbs: [ "list" ]
